# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JR_Logger_Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'JR_Logger', :path => '../'


  target 'JR_Logger_ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JR_Logger_ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
